---
# tasks file for terraform(On Linux)
# Since Ansible 2.0, 'src' parameter of 'unarchive' module accepts external URL(ex. http://example.com/file.zip).
# But this role doesn't use this feature because zip file is always downloaded even if same file already exits in local.
# http://docs.ansible.com/ansible/unarchive_module.html
- name: Download Terraform archive
  get_url:
    url: "{{ terraform_download_url }}"
    checksum: "sha256:{{ terraform_sha256 }}"
    dest: "{{ terraform_download_tmppath }}"
  register: dl_result
- name: Unarchive Terraform
  unarchive:
    src: "{{ terraform_download_tmppath }}"
    dest: "{{ terraform_bin_dir }}"
    copy: no
  become: yes
  when: dl_result.changed

- name: Download Terraformer binary
  get_url:
    url: "{{ terraformer_download_url }}"
    checksum: "sha256:{{ terraformer_sha256 }}"
    dest: "{{ terraformer_bin_dir }}/terraformer"
  become: yes
